### ISSUE TITLE
400 does not have detail

### ISSUE THREAD

**Issue by magnuswatn** [magnuswatn/wls-rest-python#1]
```
{
    "status": 400,
    "type": "http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html#sec10.4.1",
    "title": "ERRORS",
    "wls:errorsDetails": [{
        "type": "http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html#sec10.4.1",
        "title": "FAILURE",
        "detail": "Type mismatch. Cannot convert hei to weblogic.management.configuration.MachineMBean.",
        "o:errorPath": "machine"
    }]
}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wls_rest_python.py", line 349, in create
    return self._wls.post(self._url, prefer_async, **kwargs)
  File "wls_rest_python.py", line 145, in post
    return self._handle_response(response)
  File "wls_rest_python.py", line 174, in _handle_response
    self._handle_error(response)
  File "wls_rest_python.py", line 198, in _handle_error
    raise BadRequestException(response.json()['detail'])
KeyError: 'detail'
```

**Comment by magnuswatn** [comment]
Fixed in https://github.com/magnuswatn/wls-rest-python/releases/tag/v0.1.4
